### ISSUE TITLE
工程缺少sql文件

### ISSUE THREAD

**Issue by lldacing** [yukbiu/my-miaosha#2]
sql文件麻烦上传下呢

**Comment by yukbiu** [comment]
嗯，好的

**Comment by lldacing** [comment]
swagger-ui访问不了报错，安全访问没有排除- /v2/api-docs
另外，UmsMemberServiceImpl.loadUserByUsername方法上的注解缓存怎么没用啊，每次都会进这个方法

**Comment by lldacing** [comment]
> swagger-ui访问不了报错，安全访问没有排除- /v2/api-docs
> 另外，UmsMemberServiceImpl.loadUserByUsername方法上的注解缓存怎么没用啊，每次都会进这个方法

注解缓存不生效是因为内部方法调用，不走aop代理
